# Общие настройки программы
[general]
snapshot_freq = 10 # каждый N-ый слой записываем в файл
hdf5_filename = "dataset.h5" 

# Задания для вычислений

[[tasks]]
name = "elastic.small"
descr = """
Elastic wave propogation on small grid (100, 100, 100)
"""
# Настройка сетки
xdim = 100
ydim = 100
zdim = 100

dx = 1
dy = 1
dz = 1

tfin = 1.0 #s
dt = 0.01


tau = 0.0
tau_p = 0.0
tau_s = 0.0

lambda = 1.0
mu = 1.0
rho = 1.0